name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export HOST=${{ vars.HOST }}
            export PORT=${{ vars.PORT }}
            export PGHOST=${{ secrets.PGHOST }}
            export PGPORT=${{ vars.PGPORT }}
            export PGUSER=${{ secrets.PGUSER }}
            export PGDATABASE=${{ secrets.PGDATABASE }}
            export PGPASSWORD=${{ secrets.PGPASSWORD }}
            export ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}
            export REFRESH_TOKEN_KEY=${{ secrets.REFRESH_TOKEN_KEY }}
            export ACCESS_TOKEN_AGE=${{ vars.ACCESS_TOKEN_AGE }}
            
            REPO_URL=git@github.com:aodihis/node-ln.git
            APP_DIR=/home/ubuntu/app
            
            mkdir -p $APP_DIR
            cd $APP_DIR
            
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone $REPO_URL $APP_DIR
            fi
            echo $PGHOST
            echo $ACCESS_TOKEN_AGE
            git pull origin main
            npm install
            
            DATABASE_URL="postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}" npm run migrate up
            pm2 restart app
