name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            
            REPO_URL=git@github.com:aodihis/node-ln.git
            APP_DIR=/home/ubuntu/app
            
            mkdir -p $APP_DIR
            cd $APP_DIR
            
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone $REPO_URL $APP_DIR
            fi
            echo $PGHOST
            echo $ACCESS_TOKEN_AGE
            git pull origin main
            npm install
            
            echo "HOST=${{ vars.HOST }}" >> .env
            echo "PORT=${{ vars.PORT }}" >> .env
            echo "PGHOST=${{ secrets.PGHOST }}" >> .env
            echo "PGPORT=${{ vars.PGPORT }}" >> .env
            echo "PGUSER=${{ secrets.PGUSER }}" >> .env
            echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> .env
            echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> .env
            echo "ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}" >> .env
            echo "REFRESH_TOKEN_KEY=${{ secrets.REFRESH_TOKEN_KEY }}" >> .env
            echo "ACCESS_TOKEN_AGE=${{ vars.ACCESS_TOKEN_AGE }}" >> .env
            
            npm run migrate up
            pm2 restart app
